{% set name = "piff" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rmjarvis/Piff/archive/v{{ version }}.tar.gz
  sha256: d8451995140f9a37d15ded879de8a181a99c159bf4b6dd672cb2aec0dba43953

build:
  skip: true  # [win]
  number: 0
  # uses scripts so cannot be noarch
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pyyaml
    - treecorr >=4.0
    - fitsio >=1
    - matplotlib-base >=3.3.0
    - lsstdesc.coord >=1.0.5
    - galsim >=2.3
    - treegp >=0.6

test:
  requires:
    - pip
  imports:
    - piff
  commands:
    - pip check

about:
  home: https://github.com/rmjarvis/Piff
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PSFs In the Full FOV
  doc_url: http://rmjarvis.github.io/Piff/html

extra:
  recipe-maintainers:
    - beckermr
    - rmjarvis
