{% set name = "piff" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rmjarvis/Piff/archive/v{{ version }}.tar.gz
  sha256: 7d2822e08e67fca5cd75f9e1c661a5b29778db13ffa68e927a0555a75718e0a7

build:
  skip: true  # [win]
  number: 0
  # uses scripts so cannot be noarch
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pyyaml
    - treecorr >=4.0
    - fitsio >=0.9.12
    - scikit-learn >=0.18
    - matplotlib-base >=1.5.0
    - lsstdesc.coord >=1.0.5
    - galsim >=2.0
    - lmfit

test:
  imports:
    - piff

about:
  home: https://github.com/rmjarvis/Piff
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PSFs In the Full FOV
  doc_url: http://rmjarvis.github.io/Piff/html

extra:
  recipe-maintainers:
    - beckermr
    - rmjarvis
